csk/urls.py
from django.urls import path
from csk.views import *
app_name='csk'

urlpatterns=[
    path('CSK/',CSK,name='CSK'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
from india.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sahweg/',sahweg,name='sahweg'),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcb'

urlpatterns=[
    path('RCB/',RCB,name='RCB'),
]

csk/models.py
from django.db import models

# Create your models here.

india/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def CSK(request):
    return render(request,'CSK.html')

india/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def sahweg(request):
    return render(request,'sahweg.html')

rcb/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def RCB(request):
    return render(request,'RCB.html')

templates/CSK.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="background:linear-gradient(red,green,yellow,orange);color:darkmagenta">This Dhoni page</h1>
        <h1><a href="{% url 'rcb:RCB' %}">Go to virat page</a></h1>
        <h1><a href="{% url 'sahweg' %}">Go to sahweg page</a></h1>
    </center>
</body>
</html>

templates/RCB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="background:linear-gradient(red,green,yellow,orange);color:brown">This Virat</h1>
        
        <h1><a href="{% url 'csk:CSK' %}">Go to dhoni page</a></h1>
        <h1><a href="{% url 'sahweg' %}">Go to sahweg page</a></h1>
    </center>
</body>
</html>

templates/sahweg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="background:linear-gradient(red,green,yellow,orange);color:blue">This sahweg page</h1>
        <h1><a href="{% url 'csk:CSK' %}">Go to dhoni page</a></h1>
        <h1><a href="{% url 'rcb:RCB' %}">Go to virat page</a></h1>
    </center>
</body>
</html>